### ISSUE TITLE
Add scanner

### ISSUE THREAD

**Issue by dorotatomczak** [dorotatomczak/TravelPlannerApp#14]
- [x] camera handling #30 
- [x] crop and scan documents #39 
- [x] save & list scanned documents #68 
- [x] remove scan, display fulll scan when clicked and other improvements  #83
